# Call a function on error

You can use `useError` to call a function on error.

```tsx
XSWR.useError(handle, onerror) 
```

### Motivation

You want to disconnect a user when you receive a HTTP 401 (Unauthorized) error.

### Example

```tsx
function useFetchAndLogErrorMixture(handle: XSWR.Handle) {
  XSWR.useFetch(handle)
  XSWR.useError(handle, console.error)
}
```

### Implementation

```tsx
export function useError<D = any, E = any>(
  handle: Handle<D, E>,
  callback: (e: E) => void
) {
  const { error } = handle

  useEffect(() => {
    if (error !== undefined) callback(error)
  }, [error, callback])
}
```

### See also

- [useRetry](/features/use-retry) - retry on error